name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Dry-run publish
        run: cargo publish --dry-run
